### ISSUE TITLE
Examples not working out of the box

### ISSUE THREAD

**Issue by prof955** [toblum/TetrisAnimation#1]
Hi, thank you for sharing.

but Examples has missing items and gives several errors while compiling.
am i missing something?
i believe examples should work out of the box(with little changes like panel size etc of coarse).

**Comment by witnessmenow** [comment]
They should unless there is something wrong, what errors are you seeing?

**Comment by prof955** [comment]
**For eg MatrixNtpClock:**
  **there is no wifi at all.** means: can't compile at all


Multiple libraries were found for "Adafruit_GFX.h"
 Used: C:\Users\Prof955\Documents\Arduino\libraries\Adafruit_GFX_Library
 Not used: C:\Users\Prof955\Documents\Arduino\libraries\Adafruit-GFX-Library-master
exit status 1
'WiFi' was not declared in this scope

**Comment by prof955** [comment]
**MatrixEmulatedClock**

just wrote panel:  "Tetris Time"  and wait some time than crach esp:

Exception (29):
epc1=0x4020ec3b epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000019 depc=0x00000000

**Comment by prof955** [comment]
**MultipleEmulatedClocks**

exactly same problem:

just wrote panel: "Tetris Time" and wait some time than crach esp:

Exception (29):
epc1=0x4020ec3b epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000019 depc=0x00000000

**Comment by prof955** [comment]
**SetNumbers**

exactly same problem:

just wrote panel: "Tetris Time" and wait some time than crach esp:

Exception (29):
epc1=0x4020ec3b epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000019 depc=0x00000000

**Comment by prof955** [comment]
**MatrixNtpClock**
there is no wifi at all. means: can't compile at all

Multiple libraries were found for "Adafruit_GFX.h"
Used: C:\Users\Prof955\Documents\Arduino\libraries\Adafruit_GFX_Library
Not used: C:\Users\Prof955\Documents\Arduino\libraries\Adafruit-GFX-Library-master
exit status 1
'WiFi' was not declared in this scope

**Comment by prof955** [comment]
**AlphaTest**

OK not crashing.

but not doing anything too.
just wrote panel: "Tetris Letter s" (colorfull)
thats it. not freeze like that.

**Comment by witnessmenow** [comment]
You seem to have multiple versions of AdafruitGFX library installed , not
sure if that's causing any issues.

What esp8266 board are you using? Which board to you have selected in the
boards drop down? Which version of esp8266 core are you using?

**Comment by prof955** [comment]
i do have only one AdafruitGFX installed, how can i have multiple? i don't know that.
i select Adafruit Huzzah from boards.
i have lolin nodemcu v3 dev board. it has usual esp8266MOD on it.

**Comment by prof955** [comment]
![pb_lib](https://user-images.githubusercontent.com/40756158/42319985-5fe028ee-805c-11e8-8021-e2fbbff93fe8.PNG)

**Comment by prof955** [comment]
Could be it?
but i didn't get any error on other any schech

**Comment by witnessmenow** [comment]
I have a version of the esp8266 core that I got from GitHub a while ago
that crashes with the AdafruitGFX library, but using one with that I
installed through the board manager works fine.

This error says you have two, check in your libraries folder. I don't think
it's an issue though.

Multiple libraries were found for "Adafruit_GFX.h"
Used: C:\Users\Prof955\Documents\Arduino\libraries\Adafruit_GFX_Library
Not used: C:\Users\Prof955\Documents\Arduino\libraries\Adafruit-
GFX-Library-master

**Comment by prof955** [comment]
oh i saw it that and eliminated.  i copyed from github as an zip to try things some time ago. thats why itS different name. i deleted...
but as you say it not changed anything. itried. just that multiple gone.

**Comment by witnessmenow** [comment]
I'm going to close this issue as it's nearly a year old. I've set up this library on new Arduino installs without a problem.

Please comment if you want it re-opened
