### ISSUE TITLE
Support for WS2812B/NeoMatrix?

### ISSUE THREAD

**Issue by wolph** [toblum/TetrisAnimation#10]
Since the `NeoMatrix` library has an API fairly similar to the displays, it would be nice to add an example of how to use these instead. Since WS2812B leds are so ubiquitous many people will have strands (or even matrices) that would make for really nice projects :)

The library: https://github.com/adafruit/Adafruit_NeoMatrix

I had a quick go at it myself but so far my ESP32 seems to be crashing when simply plugging it in. Although I'm not 100% sure if that is due to incorrect usage or just a faulty ESP32.

**Comment by witnessmenow** [comment]
Would need more details to why this isn't working or is crashing (stack traces maybe). It should in theory work with any Adafruit GFX compatible library.
