### ISSUE TITLE
Faster block fall and block color change? Only animate changed digit?

### ISSUE THREAD

**Issue by gordonBimig** [toblum/TetrisAnimation#14]
Hi,

not sure if this is the right place :-)
I was searching for a possiblity to adjust the animation to be a bit quicker, maybe be able to change the block colors but couldn't find the place. I think it also would be nice to be able only to animate the digit which has changed, but couldn't find an option fot this either.

Am I right that those "features/whishes" aren't supported at the moment?

Regards

**Comment by clogwog** [comment]
have a look at 
https://github.com/toblum/TetrisAnimation/blob/master/examples/PxMatrix/ESP32/SetNumbers/SetNumbers.ino#L62
that might set the animation speed

i found that the time is drawn in the way you describe (see the animation at https://github.com/clogwog/tetrisclock )
are you not seeing the same ?

**Comment by gordonBimig** [comment]
Hi, thanks for your quick response.

I defined ANIMATION_TIME and set the value to 25000 (which should be faster, accordings to the description) and also 100000 (which should be slower), unfortunately I don't see any change in the animation speed.

I'm using the Tetris clock Sketch from Brian Lough:
https://github.com/witnessmenow/WiFi-Tetris-Clock

> i found that the time is drawn in the way you describe (see the animation at https://github.com/clogwog/tetrisclock )
> are you not seeing the same ?

Unfortunately not, the whole time/all digits are beeing animated every minute and this takes about 20 seconds, so 1/3 of a minute the time is hard to read :-)
That's why I'm looking for either faster animation or only animating the changed digits. I'm afraid my c++ knowledge is too limited to adapt your example to the sketch I'm using.

**Comment by gordonBimig** [comment]
> have a look at https://github.com/toblum/TetrisAnimation/blob/master/examples/PxMatrix/ESP32/SetNumbers/SetNumbers.ino#L62 that might set the animation speed
> 
> i found that the time is drawn in the way you describe (see the animation at https://github.com/clogwog/tetrisclock ) are you not seeing the same ?

timerAlarmWrite(animationTimer, 10000, true);

I reviewed the code from Brian Lough again and found a line which was calling a value of 100000, which got me thinking :-)
And well, this is the ANIMATION_TIME. Changing this value changed the animation speed. Much better now. Thanks a lot!

**Comment by clogwog** [comment]
no worries, i didn't do a lot. feel free to close the issue if it works for you.

Also i looked back through my c++ code and i'm pretty sure i didn't add any code to split up the time into h h m m individual tetristextMatrix ( https://github.com/clogwog/tetrisclock/blob/master/TetrisMatrixDraw.cpp#L515)  so i just call `TetrisMatrixDraw::setText(string txt, bool forceRefresh)` with only the txt specified and forceRefresh is set to false in the header like: 
` void setText(std::string txt, bool forceRefresh = false);`
 
 in your code just change
 https://github.com/witnessmenow/WiFi-Tetris-Clock/blob/8539f1852f74415cf0a4337ff04146657b83e778/ESP32%20or%20TinyPICO/EzTimeTetrisClockESP32/EzTimeTetrisClockESP32.ino#L70
 
```
 // If this is set to false, the number will only change if the value behind it changes
// e.g. the digit representing the least significant minute will be replaced every minute,
// but the most significant number will only be replaced every 10 minutes.
// When true, all digits will be replaced every minute.
bool forceRefresh = true;
```

to false and that should do it

**Comment by gordonBimig** [comment]
Well, this is weird. Of course I read the comments and recognized this variable, but a change did not result in the expected behaviour. Probably I didn't upload the code correctly. This time it does exactly what's described. Awesome :-)

I also solved the color issue. Found the color definition in TetrisMatrixDraw.h

So happy. Thank you for your kind support. Best regards
