### ISSUE TITLE
Can't use with PxMATRIX libray it self.

### ISSUE THREAD

**Issue by prof955** [toblum/TetrisAnimation#2]
Can't use this libray becuse it has adafruit gfx librar call in it.
also PxMATRIX has in it too.
so it gives error about using multiple libraries.

**Comment by witnessmenow** [comment]
PxMatrix is a required for the examples as it's the code that is used to
drive the display. AdafruitGFX is a required library for PxMatrix.

Readme should probably reflect this.

**Comment by prof955** [comment]
i know that.
but the problem is: when these two (PxMATRIX and TetrisAnimation) together there will be error about multiple includes.

**Comment by witnessmenow** [comment]
Ok I can take a look into that, what version of each library are you using?

**Comment by prof955** [comment]
i just got libraries 10min ago again.
also i am using PxMATRIX without a pb.

**Comment by prof955** [comment]
Sorry i forgot to mention: i am using 64x64 p3(1/32) panel.
actually i forget it because i believe it not relevant. is it?
