### ISSUE TITLE
P3 64*64 program segmentation

### ISSUE THREAD

**Issue by LilyGO** [toblum/TetrisAnimation#6]
Hey, I bought the p3 64*64 board, but I ran the example with a fault in between. Even if I modified the parameter PxMATRIX display(64, 64, P_LAT, P_OE, P_A, P_B, P_C, P_D, P_E);
But he still can't run.
Oh, 64*32 works perfectly. I am just looking for a way to run 64*64.
Thank you

![IMG_20190701_104910](https://user-images.githubusercontent.com/31160602/60407606-00d52080-9bee-11e9-8e43-3d6841e76c5b.jpg)

**Comment by witnessmenow** [comment]
Did you change the scan rate in the setup()?

I believe 64x64 are all 1/32 so it would change to

display.begin(32)

**Comment by LilyGO** [comment]
![image](https://user-images.githubusercontent.com/31160602/60414936-4d2f5900-9c0c-11e9-9178-6b8677dc4d3a.png)
I tried the change and it can be fully revealed. But only one second, it repeats reset.

**Comment by LilyGO** [comment]
![image](https://user-images.githubusercontent.com/31160602/60415160-e9596000-9c0c-11e9-9f24-f820c0e94d64.png)

**Comment by witnessmenow** [comment]
I just tested on a 64x64 and see the same issue, I will investigate it later this week

**Comment by LilyGO** [comment]
thank you

**Comment by witnessmenow** [comment]
This issue should now be fixed (at least it works for me)

I've updated the code, but this is the only thing I needed to change
```
void IRAM_ATTR display_updater() {
  portENTER_CRITICAL_ISR(&timerMux);
  display.display(10); // Was previously 70
  portEXIT_CRITICAL_ISR(&timerMux);
}
```

**Comment by LilyGO** [comment]
Successfully run, thank you so much.
