### ISSUE TITLE
Using TFT screens without flickering

### ISSUE THREAD

**Issue by robcazzaro** [toblum/TetrisAnimation#7]
I would like to use your library to build a clock with an TFT screen. I'm using one of these ESP32 boards https://github.com/Xinyuan-LilyGO/TTGO-T-Display, which have a 135x240 IPS TFT screen.

Instead of the Adafruit_GFX library I'm using the optimized https://github.com/Bodmer/TFT_eSPI library. I simply replaced references to Adafruit_GFX with TFT_eSPI and everything works well. Kudos for writing a truly general library.

The main issue I'm facing is that there's no equivalent to the VGA.show() or PDC_8544.display() function, so in the animation loop I'm forced to erase the actual screen, resulting in flickering while drawing the dropping Tetris pieces.

I know I can use the sprite object in the TFT_eSPI library to draw in RAM and quickly overlap on screen (that's my next step). But I was wondering if you thought about having your dropping pieces reset the background color while drawing a dropping piece. That would make your library working universally on any type of screen, even ones with no sprite or ability to refresh the display at once. Basically the pieces would have a background "pixel" above each drawn pixel, and instead of leaving a trace of color behind, would simply restore the background. I understand that this would not work with variable color background (say, a bitmap as background), but given how busy a display with dropping Tetris pieces already is, I'd say it's an acceptable compromise

If interested, I can attach my example once I get it working (sprite or not)

**Comment by witnessmenow** [comment]
I know this is a really old issue at this stage, but this would be a pretty big change for this library and think it would probably just be a fork instead.
